BookStore_Core/BookStore_Core/Models/Sach.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStore_Core.Models
{
    public class Sach
    {
        [Key]
        [Display(Name = "Id")]
        public string SachId { get; set; }
        [Display(Name = "Tên sách")]
        [Required(ErrorMessage = "Bắt buộc nhập tên sách")]
        public string TenSach { get; set; }
        [Display(Name = "Lượt xem")]
        public int LuotXem { get; set; }
        [Display(Name = "Hình ảnh")]
        public string HinhAnh { get; set; }
        public string LoaiSachCTId { get; set; }
        public string TacGiaId { get; set; }
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
        [Display(Name = "Lượt đánh giá")]
        public int LuotDanhGia { get; set; }
        public int SaoTrungBinh { get; set; }
        public int LuotThich { get; set; }
        public DateTime NgayTao { get; set; }
        public string KichThuoc { get; set; }
        public string LoaiBia { get; set; }
        public int TrongLuong { get; set; }
        public int SoTrang { get; set; }
        public bool IsDel { get; set; }
        public virtual LoaiSachCuThe LoaiSachCuThe { get; set; }
        [NotMapped]
        public List<BangGia> BangGias { get; set; }
        //[NotMapped]
        //public List<BookUpdate> BookUpdates { get; set; }
        [NotMapped]
        public List<Cart> Carts { get; set; }
        [ForeignKey("TacGiaId")]
        public virtual TacGia TacGia { get; set; }
        [NotMapped]
        public List<SachDuocThich> SachDuocThichs { get; set; }
        [NotMapped]
        public List<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [NotMapped]
        public List<AnhPhu> AnhPhus { get; set; }
        [NotMapped]
        public List<KhachHangThich> KhachHangThiches { get; set; }
    }
}

BookStore_Core/BookStore_Core/Models/SachViewModel.cs
using System.Collections.Generic;

namespace BookStore_Core.Models
{
    public class SachViewModel
    {
        public Sach Sach { get; set; }
        public BangGia BangGia { get; set; }
        public SachDuocThich SachDuocThich { get; set; }
        public List<AnhPhu> AnhPhus { get; set; }
        public int SoSachBanDuoc { get; set; }
        public string TrangThai { get; set; }
    }
}

BookStore_Core/BookStore_Core/Areas/Admin/Controllers/SachesController.cs
using BookStore_Core.DAL;
using BookStore_Core.Models;
using BookStore_Core.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore_Core.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Saches")]
    public class SachesController : Controller
    {
        private readonly IHostingEnvironment _he;
        private readonly BookStoreContext _context;
        public string linkAnhChinh = "";
        public string linkAnhPhu1 = "";
        public string linkAnhPhu2 = "";
        public string linkAnhPhu3 = "";
        public int Gia;

        public SachesController(BookStoreContext context, IHostingEnvironment he)
        {
            _he = he;
            _context = context;
        }

        // GET: Admin/Saches
        [Route("index")]
        public async Task<IActionResult> Index()
        {
            var bookStoreContext = _context.Saches.Include(s => s.LoaiSachCuThe).Include(s => s.TacGia).Where(p => p.IsDel == false);
            return View(await bookStoreContext.ToListAsync());
        }

        // GET: Admin/Saches/Details/5
        [Route("Details/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sach = await _context.Saches
                .Include(s => s.LoaiSachCuThe)
                .Include(s => s.TacGia)
                .FirstOrDefaultAsync(m => m.SachId == id);
            var bangGia = _context.BangGias.Include(s => s.KhuyenMai)
                .Where(p => p.SachId == sach.SachId && p.IsDel == false).FirstOrDefault();
            var anhPhu = _context.AnhPhus.Where(p => p.SachId == sach.SachId).ToList();
            if (sach == null)
            {
                return NotFound();
            }
            SachViewModel sachVM = new SachViewModel() { AnhPhus = anhPhu, Sach = sach, BangGia = bangGia };
            return View(sachVM);
        }


        // GET: Admin/Saches/Create
        [Route("Create")]
        public IActionResult Create()
        {
            ViewData["LoaiSachCTId"] = new SelectList(_context.LoaiSachCuThes, "LoaiSachCTId", "TenLoaiSachCT");
            ViewData["TacGiaId"] = new SelectList(_context.TacGias, "TacGiaId", "TenTacGia");

            return View();
        }

        // POST: Admin/Saches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ThemSachViewModel sachVM, IFormFile file1, IFormFile file2, IFormFile file3)
        {
            if (ModelState.IsValid)
            {

                var stringDate = DateTime.Now.ToString();
                stringDate = stringDate.Replace(":", ".");
                stringDate = stringDate.Replace(" ", ".");
                stringDate = stringDate.Replace("/", ".");
                var fileName = stringDate + Path.GetFileName(sachVM.file.FileName);
                var path = Path.Combine(_he.WebRootPath, "BookImages", Path.GetFileName(fileName));
                var stream = new FileStream(path, FileMode.Create);
                await sachVM.file.CopyToAsync(stream);
                sachVM.Sach.HinhAnh = fileName;
                


                //Tạo Id cho sách
                var tam = _context.Saches.ToList().Count;
                var lastId = tam + 1;
                string Idtam = "";
                var soChuSo = 0;
                while (tam > 0)
                {
                    tam = tam / 10;
                    soChuSo++;

                }
                int dem = 8 - soChuSo;
                for (int i = 0; i < dem; i++)
                {
                    Idtam += "0";
                }
                Idtam = "SACH" + Idtam + lastId;
                sachVM.Sach.SachId = Idtam;
                sachVM.Sach.NgayTao = DateTime.Today;
                _context.Add(sachVM.Sach);
                await _context.SaveChangesAsync();

                //Thêm bảng giá mới cho sách mới
                _context.Add(new BangGia() { SachId = Idtam, DonGia = sachVM.BangGia.DonGia, NgayCoHieuLuc = DateTime.Now });
                await _context.SaveChangesAsync();

                //Lưu ảnh nhỏ vào database
                //Ảnh nhỏ thứ 1
                if (file1 != null)
                {
                    var fileName1 = stringDate + "AnhNho1" + Path.GetFileName(file1.FileName);
                    var path1 = Path.Combine(_he.WebRootPath, "BookImages", Path.GetFileName(fileName1));
                    var stream1 = new FileStream(path1, FileMode.Create);
                    await file1.CopyToAsync(stream1);
                    _context.AnhPhus.Add(new AnhPhu() { HinhAnh = fileName1, SachId = Idtam });
                    await _context.SaveChangesAsync();
                }
                //Ảnh nhỏ thứ 2
                if (file2 != null)
                {
                    var fileName2 = stringDate + "AnhNho2" + Path.GetFileName(file1.FileName);
                    var path2 = Path.Combine(_he.WebRootPath, "BookImages", Path.GetFileName(fileName2));
                    var stream2 = new FileStream(path2, FileMode.Create);
                    await file2.CopyToAsync(stream2);
                    _context.AnhPhus.Add(new AnhPhu() { HinhAnh = fileName2, SachId = Idtam });
                    await _context.SaveChangesAsync();
                }
                if (file3 != null)
                {
                    var fileName3 = stringDate + "AnhNho3" + Path.GetFileName(file1.FileName);
                    var path3 = Path.Combine(_he.WebRootPath, "BookImages", Path.GetFileName(fileName3));
                    var stream3 = new FileStream(path3, FileMode.Create);
                    await file3.CopyToAsync(stream3);
                    _context.AnhPhus.Add(new AnhPhu() { HinhAnh = fileName3, SachId = Idtam });
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            //sachVM.Sach.HinhAnh = sachVM.file.FileName;
            ViewData["LoaiSachCTId"] = new SelectList(_context.LoaiSachCuThes, "LoaiSachCTId", "TenLoaiSachCT", sachVM.Sach.LoaiSachCTId);
            ViewData["TacGiaId"] = new SelectList(_context.TacGias, "TacGiaId", "TenTacGia", sachVM.Sach.TacGiaId);
            return View(sachVM);
        }
        [Route("Edit/{id}")]
        // GET: Admin/Saches/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sach = await _context.Saches
                .Include(s => s.LoaiSachCuThe)
                .Include(s => s.TacGia)
                .FirstOrDefaultAsync(m => m.SachId == id && m.IsDel == false);
            if (sach == null)
            {
                return NotFound();
            }
            var bangGia = _context.BangGias.Include(s => s.KhuyenMai)
                .Where(p => p.SachId == sach.SachId && p.IsDel == false).FirstOrDefault();
            var anhPhu = _context.AnhPhus.Where(p => p.SachId == sach.SachId).ToList();
            if (sach == null)
            {
                return NotFound();
            }
            ThemSachViewModel sachVM = new ThemSachViewModel() { AnhPhus = anhPhu, Sach = sach, BangGia = bangGia };
            Gia = bangGia.DonGia;
            linkAnhChinh = sach.HinhAnh;
            ViewData["LoaiSachCTId"] = new SelectList(_context.LoaiSachCuThes, "LoaiSachCTId", "TenLoaiSachCT", sach.LoaiSachCTId);
            ViewData["TacGiaId"] = new SelectList(_context.TacGias, "TacGiaId", "TenTacGia", sach.TacGiaId);
            return View(sachVM);
        }

        // POST: Admin/Saches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Edit/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ThemSachViewModel sachVM, IFormFile photo1, IFormFile photo2, IFormFile photo3)
        {
            if (id != sachVM.Sach.SachId)
            {
                return NotFound();
            }
            try
            {
                var stringDate = DateTime.Now.ToString();
                stringDate = stringDate.Replace(":", ".");
                stringDate = stringDate.Replace(" ", ".");
                stringDate = stringDate.Replace("/", ".");
                if (sachVM.file != null)
                {
                    var fileName = stringDate + Path.GetFileName(sachVM.file.FileName);
                    var path = Path.Combine(_he.WebRootPath, "BookImages", Path.GetFileName(fileName));
                    var stream = new FileStream(path, FileMode.Create);
                    await sachVM.file.CopyToAsync(stream);
                    sachVM.Sach.HinhAnh = fileName;
                }
                else
                {
                    sachVM.Sach.HinhAnh = sachVM.Sach.HinhAnh;
                }

                //Xử lý ảnh nhỏ 1
                if (photo1 != null)
                {
                    var fileName = stringDate + Path.GetFileName(photo1.FileName);
                    var path = Path.Combine(_he.WebRootPath, "BookImages", Path.GetFileName(fileName));
                    var stream = new FileStream(path, FileMode.Create);
                    await photo1.CopyToAsync(stream);

BookStore_Core/BookStore_Core/Views/Saches/HienThiSachCuThe.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model BookStore_Core.ViewModel.PaginatedList<SachViewModel>
@{
    Layout = "/Views/Shared/_Layout3.cshtml";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<!-- Main wrapper -->
<!-- Header -->
<!-- //Header -->
<!-- Start Search Popup -->
<!-- End Search Popup -->
<!-- Start Bradcaump area -->
<div class="ht__bradcaump__area bg-image--6">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Hiển thị theo thể loại</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="/Home">Trang chủ</a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- Start Shop Page -->
<div class="page-shop-sidebar left--sidebar bg--white section-padding--lg">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-12 order-2 order-lg-1 md-mt-40 sm-mt-40">
                <div class="shop__sidebar">
                    <aside class="wedget__categories poroduct--cat">
                        <span style="font-family:Tahoma">Thể loại</span>
                        <h3 class="wedget__title">@ViewBag.TenTheLoaiTongQuat</h3>
                        <ul>
                            @for (int i = 0; i < @ViewBag.TheLoaiCuThe.Count; i++)
                            {
                                <li><a href="/Saches/HienThiSachCuThe/@ViewBag.TheLoaiCuThe[i].LoaiSachCTId"> @ViewBag.TheLoaiCuThe[i].TenLoaiSachCT <span>(@ViewBag.SoLuongSP[i])</span></a></li>
                            }
                        </ul>
                    </aside>
                    <aside class="wedget__categories pro--range">
                        <h3 class="wedget__title">Filter by price</h3>
                        <div class="content-shopby">
                            <div class="price_filter s-filter clear">
                                <form action="#" method="GET">
                                    <div id="slider-range"></div>
                                    <div class="slider__range--output">
                                        <div class="price__output--wrap">
                                            <div class="price--output">
                                                <span>Price :</span><input type="text" id="amount" readonly="">
                                            </div>
                                            <div class="price--filter">
                                                <a href="#">Filter</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </aside>
                    <aside class="wedget__categories poroduct--tag">
                        <h3 class="wedget__title">Product Tags</h3>
                        <ul>
                            <li><a href="#">Biography</a></li>
                            <li><a href="#">Business</a></li>
                            <li><a href="#">Cookbooks</a></li>
                            <li><a href="#">Health & Fitness</a></li>
                            <li><a href="#">History</a></li>
                            <li><a href="#">Mystery</a></li>
                            <li><a href="#">Inspiration</a></li>
                            <li><a href="#">Religion</a></li>
                            <li><a href="#">Fiction</a></li>
                            <li><a href="#">Fantasy</a></li>
                            <li><a href="#">Music</a></li>
                            <li><a href="#">Toys</a></li>
                            <li><a href="#">Hoodies</a></li>
                        </ul>
                    </aside>
                    <aside class="wedget__categories sidebar--banner">
                        <img src="~/Template/images/others/banner_left.jpg" alt="banner images">
                        <div class="text">
                            <h2>new products</h2>
                            <h6>save up to <br> <strong>40%</strong>off</h6>
                        </div>
                    </aside>
                </div>
            </div>
            <div class="col-lg-9 col-12 order-1 order-lg-2">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shop__list__wrapper d-flex flex-wrap flex-md-nowrap justify-content-between">
                            <div class="shop__list nav justify-content-center" role="tablist">
                                <a class="nav-item nav-link active" data-toggle="tab" href="#nav-grid" role="tab"><i class="fa fa-th"></i></a>
                                @*<a class="nav-item nav-link" data-toggle="tab" href="#nav-list" role="tab"><i class="fa fa-list"></i></a>*@
                            </div>
                            <p>Hiển thị 1–9 trong @Model.Count kết quả</p>
                            <div class="orderby__wrapper">
                                @*<span>Sort By</span>
                                    <select class="shot__byselect">
                                        <option>Default sorting</option>
                                        <option>HeadPhone</option>
                                        <option>Furniture</option>
                                        <option>Jewellery</option>
                                        <option>Handmade</option>
                                        <option>Kids</option>
                                    </select>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab__container">
                    <div class="shop-grid tab-pane fade show active" id="nav-grid" role="tabpanel">
                        <div class="row">
                            <!-- Start Single Product -->
                            @foreach (var x in Model)
                            {
                                <div class="product product__style--3 col-lg-4 col-md-4 col-sm-6 col-12">
                                    <div class="product__thumb">
                                        <a class="first__img" href="/Saches/Details/@x.Sach.SachId"><img height="300" width="300" src="~/BookImages/@x.Sach.HinhAnh" alt="product image"></a>
                                        <a class="second__img animation1" href="/Saches/Details/@x.Sach.SachId"><img height="300" width="300" src="~/BookImages/@x.Sach.HinhAnh" alt="product image"></a>
                                        <div class="hot__box">
                                            @if (x.BangGia.PhanTramKhuyenMai > 0)
                                            {
                                                <span class="hot-label">@x.BangGia.PhanTramKhuyenMai %</span>
                                            }
                                            else
                                            {
                                                <span class="hot-label">Mới</span>
                                            }
                                        </div>
                                    </div>
                                    <div class="product__content content--center">
                                        <h4><a href="single-product.html">@x.Sach.TenSach</a></h4>
                                        <ul class="prize d-flex">
                                            @if (x.BangGia.PhanTramKhuyenMai > 0)
                                            {
                                                <li>@(x.BangGia.DonGia - x.BangGia.PhanTramKhuyenMai * x.BangGia.DonGia / 100)  VND</li>
                                                <li class="old_prize">@x.BangGia.DonGia</li>
                                            }
                                            else
                                            {
                                                <li>@x.BangGia.DonGia VND</li>
                                            }
                                        </ul>
                                        <div class="action">
                                            <div class="actions_inner">
                                                <ul class="add_to_links">
                                                    <li><a class="cart" href="cart.html"><i class="bi bi-shopping-bag4"></i></a></li>
                                                    <li><a class="wishlist" href="wishlist.html"><i class="bi bi-shopping-cart-full"></i></a></li>
                                                    <li><a class="compare" href="#"><i class="bi bi-heart-beat"></i></a></li>
                                                    <li><a data-toggle="modal" title="Quick View" class="quickview modal-view detail-link" href="#productmodal"><i class="bi bi-search"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product__hover--content">
                                            <ul class="rating d-flex">
                                                @for (int i = 0; i < x.Sach.SaoTrungBinh; i++)
                                                {
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                }
                                                @for (int i = 0; i < 5 - x.Sach.SaoTrungBinh; i++)
                                                {
                                                    <li><i class="fa fa-star-o"></i></li>
                                                }
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                            }

                            <!-- End Single Product -->

                        </div>
                        <ul class="wn__pagination">
                            @if (@prevDisabled == "")
                            {
                                <li>
                                    <a asp-route-page="@(Model.PageIndex - 1)"><i class="zmdi zmdi-chevron-left"></i></a>
                                </li>
                            }
                            @{
                                int k = 1;
                                if (ViewBag.Trang / 4 > 1 && ViewBag.Trang % 4 > 1)
                                {
                                    k++;
                                }
                                @for (var i = k; i < 4 + ViewBag.Trang && i <= ViewBag.Max; i++)
                                {
                                    if (i == ViewBag.Trang)
                                    {
                                        <li class="active"><a asp-action="HienThiSachCuThe" asp-controller="Saches" asp-route-page="@i">@i</a></li>
                                    }
                                    else
                                    {
                                        <li><a asp-action="HienThiSachCuThe" asp-controller="Saches" asp-route-page="@i">@i</a></li>
                                    }
                                }
                            }

                            @if (nextDisabled == "")
                            {
                                <li>
                                    <a asp-route-page="@(Model.PageIndex + 1)"><i class="zmdi zmdi-chevron-right"></i></a>
                                </li>
                            }
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Shop Page -->
<!-- Footer Area -->
<!-- //Footer Area -->