BookStore_Core/BookStore_Core/Models/Employee.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BookStore_Core.Models
{
    public class Employee
    {
        [Key]
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public DateTime BirthDay { get; set; }
        public DateTime LastUpdate { get; set; }
        public bool IsDel { get; set; }
    }
}

BookStore_Core/BookStore_Core/Areas/Admin/Controllers/EmployeesController.cs
using BookStore_Core.DAL;
using BookStore_Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore_Core.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Employees")]
    public class EmployeesController : Controller
    {
        private readonly BookStoreContext _context;

        public EmployeesController(BookStoreContext context)
        {
            _context = context;
        }
        [Route("Index")]
        // GET: Admin/Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.Where(p => p.IsDel == false).ToListAsync());
        }
        [Route("Details")]
        // GET: Admin/Employees/Details/5
        public async Task<IActionResult> Details(string id, string email)
        {
            if (id == null && email == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id || m.Email == email);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }
        [Route("Create")]
        // GET: Admin/Employees/Create
        public IActionResult Create()
        {
            return View();
        }
        [Route("Create")]
        // POST: Admin/Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,EmployeeName,Email,Phone,Address,BirthDay,LastUpdate,IsDel")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                var checkUserName = _context.Employees.Where(p => p.Email == employee.Email).FirstOrDefault();

                if (checkUserName == null)
                {
                    if (_context.Employees.Any() == false)
                    {
                        employee.EmployeeId = "EMP0000001";
                    }
                    else
                    {
                        var tam = _context.Employees.ToList().Count;
                        string Idtam = "";
                        var lastId = tam + 1;

                        var soChuSo = 0;
                        while (tam > 0)
                        {
                            tam = tam / 10;
                            soChuSo++;

                        }
                        int dem = 7 - soChuSo;
                        //Idtam += "CUS";
                        for (int i = 0; i < dem; i++)
                        {
                            Idtam = "0" + Idtam;
                        }
                        Idtam = "EMP" + Idtam + lastId;
                        employee.EmployeeId = Idtam;
                    }
                    await _context.Employees.AddAsync(new Employee()
                    {
                        EmployeeId = employee.EmployeeId,
                        EmployeeName = employee.EmployeeName,
                        Email = employee.Email,
                        Address = employee.Address,
                        Phone = employee.Phone,
                        BirthDay = employee.BirthDay,
                        LastUpdate = DateTime.Now,
                        IsDel = false
                    });
                    await _context.Logins.AddAsync(new Login() { LoginName = employee.Email, Password = "123", RoleId = 2, ResetPassword = "1", LastUpdate = DateTime.Now, IsDel = true });
                    //_context.Add(employee);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(employee);
        }
        [Route("Edit")]
        // GET: Admin/Employees/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }
        [Route("Edit")]
        // POST: Admin/Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("EmployeeId,EmployeeName,Email,Phone,Address,BirthDay,IsDel")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    employee.LastUpdate = DateTime.Now;
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }
        [Route("Delete")]
        // GET: Admin/Employees/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }
        [Route("Delete")]
        // POST: Admin/Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var employee = await _context.Employees.SingleOrDefaultAsync(p => p.EmployeeId == id);
            employee.IsDel = true;
            _context.Update(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Route("NangCap")]
        // GET: Admin/Employees/Edit/5
        public async Task<IActionResult> NangCap(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }
        [Route("NangCap")]
        // POST: Admin/Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NangCap(string id, Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var emp = _context.Employees.SingleOrDefault(p => p.EmployeeId == id);
                    Manager manager = new Manager();
                    if (_context.Managers.Any() == false)
                    {
                        manager.ManagerId = "MAG0000001";
                    }
                    else
                    {
                        var tam = _context.Managers.ToList().Count;
                        string Idtam = "";
                        var lastId = tam + 1;

                        var soChuSo = 0;
                        while (tam > 0)
                        {
                            tam = tam / 10;
                            soChuSo++;

                        }
                        int dem = 7 - soChuSo;
                        //Idtam += "CUS";
                        for (int i = 0; i < dem; i++)
                        {
                            Idtam = "0" + Idtam;
                        }
                        Idtam = "CUS" + Idtam + lastId;

                        manager.ManagerId = Idtam;
                        emp.LastUpdate = DateTime.Now;
                        emp.IsDel = true;
                        _context.Update(emp);
                        await _context.SaveChangesAsync();

                        _context.Managers.Add(new Manager() { ManagerId = Idtam, Email = emp.Email, ManagerName = emp.EmployeeName, BirthDay = emp.BirthDay, Phone = emp.Phone, Address = emp.Address, LastUpdate = DateTime.Now });
                        await _context.SaveChangesAsync();
                        var login = _context.Logins.SingleOrDefault(p => p.LoginName == emp.Email);
                        login.RoleId = 1;
                        _context.Logins.Update(login);
                        await _context.SaveChangesAsync();
                        return RedirectToAction("Index", "Managers");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;

BookStore_Core/BookStore_Core/Areas/Admin/Views/Employees/Create.cshtml
@model BookStore_Core.Models.Employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <h1 style="text-align: center">
        <b>Create</b>
    </h1>

    <h4 style="text-align: center">
        <b>Employee</b>
    </h4>
<hr />

<div style="padding-left:350px" class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <b>
                    <label asp-for="EmployeeName" class="control-label"></label>
                </b>
                <input asp-for="EmployeeName" class="form-control" />
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>
                    <label asp-for="Email" class="control-label"></label>
                </b>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>
                    <label asp-for="Phone" class="control-label"></label>
                </b>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>
                    <label asp-for="Address" class="control-label"></label>
                </b>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>
                    <label asp-for="BirthDay" class="control-label"></label>
                </b>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="LastUpdate" class="control-label"></label>
                <input asp-for="LastUpdate" class="form-control" />
                <span asp-validation-for="LastUpdate" class="text-danger"></span>
            </div>*@
            @*<div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDel" /> @Html.DisplayNameFor(model => model.IsDel)
                </label>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<hr />
<div style="text-align: center">
    <b><a asp-action="Index">Back to List</a></b>
</div>

BookStore_Core/BookStore_Core/Areas/Admin/Views/Employees/Delete.cshtml
@model BookStore_Core.Models.Employee

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align: center">
    <b>Delete</b>
</h1>
<hr />
<h3 style="text-align: center">
    <b>Are you sure you want to delete this?</b>
</h3>

<h4 style="text-align: center">
    <b>Employee</b>
</h4>

<hr />

<div>
    <dl style="padding-left:250px" class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsDel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsDel)
        </dd>
    </dl>
</div>

<hr />
<form style="text-align: center" asp-action="Delete" asp-route-id="@Model.EmployeeId">
    <input type="hidden" asp-for="EmployeeId" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <b><a asp-action="Index">Back to List</a></b>
</form>

BookStore_Core/BookStore_Core/Areas/Admin/Views/Employees/Details.cshtml
@model BookStore_Core.Models.Employee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align: center">
    <b>Details</b>
</h1>
<h4 style="text-align: center">
    <b>Employee</b>
</h4>
<hr />
<div>
    <dl style="padding-left:250px" class="row">
        <dt class = "col-sm-2">
            Tên nhân viên
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>
        <dt class = "col-sm-2">
            Email
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            SDT
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
           Địa chỉ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            Sinh nhật
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class = "col-sm-2">
            Cập nhật ngày
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>

    </dl>
</div>
<hr />
<div style="text-align: center">
    <b>
        <a asp-action="Edit" asp-controller="Employees" asp-area="Admin" asp-route-id="@Model.EmployeeId">Sửa</a> |
        <a asp-action="Index" asp-controller="AdminMenus" asp-area="Admin">Về trang chủ</a>
    </b>
</div>
<hr />

BookStore_Core/BookStore_Core/Areas/Admin/Views/Employees/Edit.cshtml
@model BookStore_Core.Models.Employee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align: center">
    <b>Edit</b>
</h1>

<h4 style="text-align: center">
    <b>Employee</b>
</h4>
<hr />
<div style="padding-left:350px" class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Employees" asp-area="Admin" asp-route-id="@Model.EmployeeId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmployeeId" />
            <input type="hidden" asp-for="Email" />
            
            <div class="form-group">
                <b>
                    <label asp-for="EmployeeName" class="control-label"></label>
                </b>
                <input asp-for="EmployeeName" class="form-control" />
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <b>
                    <label asp-for="Phone" class="control-label"></label>
                </b>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>
                    <label asp-for="Address" class="control-label"></label>
                </b>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>
                    <label asp-for="BirthDay" class="control-label"></label>
                </b>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="LastUpdate" class="control-label"></label>
                <input asp-for="LastUpdate" class="form-control" />
                <span asp-validation-for="LastUpdate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDel" /> @Html.DisplayNameFor(model => model.IsDel)
                </label>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Lưu lại" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<hr />
<div style="text-align: center">
    <b>
        <a asp-action="Index" asp-controller="AdminMenus" asp-area="Admin">Về trang chủ</a>
    </b>
</div>
<hr />

BookStore_Core/BookStore_Core/Areas/Admin/Views/Employees/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model IEnumerable<BookStore_Core.Models.Employee>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Tất cả quản lý</h6>
                        <hr />
                        @if (HttpContextAccessor.HttpContext.Session.GetString("RoleId").ToString() == "1")
                        {
                            <p>
                                <a asp-action="Create">Thêm nhân viên</a>
                            </p>
                        }
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Mã nhân viên</th>
                                        <th>Tên nhân viên</th>
                                        <th>Email</th>
                                        <th>SDT</th>
                                        <th>Địa chỉ</th>
                                        <th>Sinh nhật</th>
                                        <th>Cập nhật</th>
                                        @if (HttpContextAccessor.HttpContext.Session.GetString("RoleId").ToString() == "1")
                                        {
                                            <th>chỉnh sửa</th>
                                        }

                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Mã nhân viên</th>
                                        <th>Tên nhân viên</th>
                                        <th>Email</th>
                                        <th>SDT</th>
                                        <th>Địa chỉ</th>
                                        <th>Sinh nhật</th>
                                        <th>Cập nhật</th>
                                        @if (HttpContextAccessor.HttpContext.Session.GetString("RoleId").ToString() == "1")
                                        {
                                            <th>chỉnh sửa</th>
                                        }
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(a => item.EmployeeId)</td>
                                            <td>@Html.DisplayFor(a => item.EmployeeName)</td>
                                            <td>@Html.DisplayFor(a => item.Email)</td>
                                            <td>@Html.DisplayFor(a => item.Phone)</td>
                                            <td>@Html.DisplayFor(a => item.Address)</td>
                                            <td>@Html.DisplayFor(a => item.BirthDay)</td>

                                            <td>@Html.DisplayFor(a => item.LastUpdate)</td>
                                            @if (HttpContextAccessor.HttpContext.Session.GetString("RoleId").ToString() == "1")
                                            {
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.EmployeeId">Sửa</a> |
                                            <a asp-action="Details" asp-route-id="@item.EmployeeId">Chi tiết</a> |
                                            <a asp-action="Delete" asp-route-id="@item.EmployeeId">Xóa</a> |
                                            <a asp-action="NangCap" asp-route-id="@item.EmployeeId">Nâng cấp</a>
                                        </td>
                                            }

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->


    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

BookStore_Core/BookStore_Core/Areas/Admin/Views/Employees/NangCap.cshtml
@model BookStore_Core.Models.Employee

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align: center">
    <b>Promotion</b>
</h1>

<h3 style="text-align: center">
    <b>Bạn có muốn thăng chức cho nhân viên này lên quản lý ko?</b>
</h3>
<hr />
    <h4 style="text-align: center">
        <b>Employee</b>
    </h4>
<hr />
<div>
    <dl style="padding-left:350px" class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsDel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsDel)
        </dd>
    </dl>

    <hr />
    <form style="text-align: center" asp-action="NangCap" asp-route-id="@Model.EmployeeId">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Nâng cấp" class="btn btn-danger" /> |
        <b>
            <a asp-action="Index">Back to List</a>
        </b>
    </form>
</div>