BookStore_Core/BookStore_Core/Controllers/ShoppingCartController.cs
using BookStore_Core.DAL;
using BookStore_Core.Models;
using BookStore_Core.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;

namespace BookStore_Core.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly BookStoreContext _context;
        // GET: ShoppingCart
        public ShoppingCartController(BookStoreContext context)
        {
            _context = context;
        }
        public ActionResult AddToShoppingCart(string id, int qty)
        {
            if (HttpContext.Session.GetString("UserName") == null || HttpContext.Session.GetString("UserName") == "")
            {
                HttpContext.Session.SetString("IdSach", id);
                return RedirectToAction("Login", "Account", new { id = id });
            }

            if (HttpContext.Session.GetString("RoleId").ToString() == "1" || HttpContext.Session.GetString("RoleId").ToString() == "3")
            {
                return RedirectToAction("Details", "Saches", new { id = id });
            }
            var cusId = HttpContext.Session.GetString("UserName").ToString();
            var user = _context.Customers.Where(p => p.CustomerEmail == cusId).SingleOrDefault();
            if (_context.Carts.Any() == false)
            {
                _context.Carts.Add(new Cart() { CustomerId = user.CustomerId, SachId = id, Amount = qty });
                _context.SaveChanges();
                return RedirectToAction("Details", "Saches", new { id = id });
            }
            var cart = _context.Carts.Where(p => p.CustomerId == user.CustomerId);
            if (cart.Any() == false)
            {
                _context.Carts.Add(new Cart() { CustomerId = user.CustomerId, SachId = id, Amount = qty });
                _context.SaveChanges();
                return RedirectToAction("Details", "Saches", new { id = id });
            }
            bool isFindSameBook = false;
            Cart tam = new Cart();
            foreach (var x in cart)
            {
                if (x.SachId == id)
                {
                    tam = x;
                    isFindSameBook = true;
                    break;
                }
            }
            tam.Amount += qty;
            _context.Carts.Update(tam);
            _context.SaveChanges();
            if (isFindSameBook)
            {
                _context.SaveChanges();
                return RedirectToAction("Details", "Saches", new { id = id });
            }
            _context.Carts.Add(new Cart() { CartId = DateTime.Now, CustomerId = user.CustomerId, SachId = id, Amount = qty });
            _context.SaveChanges();
            return RedirectToAction("Details", "Saches", new { id = id });
        }

        public IActionResult ThanhToan()
        {

            List<ShoppingCartViewModel> cartVM = new List<ShoppingCartViewModel>();
            var acc = HttpContext.Session.GetString("UserName").ToString();
            var khachHang = _context.Customers.FirstOrDefault(p => p.CustomerEmail == acc);
            var cart = _context.Carts.Include(p => p.Customer).Include(p => p.Sach).Where(p => p.CustomerId == khachHang.CustomerId);
            int[] soLuong = new int[cart.Count()];
            int i = 0;
            foreach (var x in cart)
            {
                var bangGia = _context.BangGias.LastOrDefault(p => p.SachId == x.SachId);
                cartVM.Add(new ShoppingCartViewModel() { Cart = x, BangGia = bangGia, GiaTong = x.Amount * (bangGia.DonGia - bangGia.DonGia * bangGia.PhanTramKhuyenMai / 100) });
                soLuong[i] = x.Amount;
                i++;
            }
            ViewBag.SoLuong = soLuong;
            return View(cartVM);
        }
        [HttpPost]
        public IActionResult KetThucThanhToan(int[] SoLuong, string stripeEmail, string stripeToken)
        {
            var customers = new CustomerService();
            var charges = new ChargeService();
            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });
            //int a = SoLuong[0];
            var cus = _context.Customers.Where(p => p.CustomerEmail == HttpContext.Session.GetString("UserName").ToString()).FirstOrDefault();
            var hoaDon = new HoaDon() { HoaDonId = DateTime.Now, CustomerId = cus.CustomerId, TrangThai = -1 };
            _context.HoaDons.Add(hoaDon);
            _context.SaveChanges();
            int tongTien = 0;
            var cart = _context.Carts.Where(p => p.CustomerId == cus.CustomerId);
            int i = 0;
            foreach (var x in cart)
            {
                var gia = _context.BangGias.LastOrDefault(p => p.SachId == x.SachId);
                _context.ChiTietHoaDons.Add(new ChiTietHoaDon() { HoaDonId = hoaDon.HoaDonId, SachId = x.SachId, SoLuong = SoLuong[i], TongTien = SoLuong[i] * (gia.DonGia - gia.DonGia * gia.PhanTramKhuyenMai / 100) });
                tongTien += SoLuong[i] * (gia.DonGia - gia.DonGia * gia.PhanTramKhuyenMai / 100);
                _context.Remove(x);
                i++;
            }
            if (cus.DiemSo >= 10000)
            {
                tongTien -= tongTien * 20 / 100;
            }
            else if (cus.DiemSo >= 5000)
            {
                tongTien -= tongTien * 10 / 100;
            }
            else if (cus.DiemSo >= 1000)
            {
                tongTien -= tongTien * 5 / 100;
            }
            hoaDon.TongTien = tongTien;
            _context.Update(hoaDon);
            _context.SaveChanges();
            var charge = charges.Create(new ChargeCreateOptions
            {
                Amount = tongTien,
                Description = "Test Payment",
                Currency = "VND",
                CustomerId = customer.Id
            });
            if (charge.Status == "succeeded")
            {
                string BalanceTransactionId = charge.BalanceTransactionId;
                RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

BookStore_Core/BookStore_Core/Views/ShoppingCart/ThanhToan.cshtml
@model IEnumerable<BookStore_Core.ViewModel.ShoppingCartViewModel>
@{
    ViewData["Title"] = "ThanhToan";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}

<!-- Main wrapper -->
<!-- Header -->
<!-- //Header -->
<!-- Start Search Popup -->
<!-- End Search Popup -->
<!-- Start Bradcaump area -->
<div class="ht__bradcaump__area bg-image--3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Shopping Cart</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="index.html">Home</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Shopping Cart</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- cart-main-area start -->
<div class="cart-main-area section-padding--lg bg--white">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 ol-lg-12">
                <form asp-action="KetThucThanhToan">
                    <div class="table-content wnro__table table-responsive">
                        <table>
                            <thead>
                                <tr class="title-top">
                                    <th class="product-thumbnail">Hình ảnh</th>
                                    <th class="product-name">Tên sách</th>
                                    <th class="product-price">Price</th>
                                    <th class="product-quantity">Số lượng</th>
                                    <th class="product-subtotal">Giá</th>
                                    @*<th class="product-remove">Xóa</th>*@
                                </tr>
                            </thead>

                            <tbody>

                                @foreach (var x in Model)
                                {
                                    <tr>
                                        <td class="product-thumbnail"><a href="#"><img src="~/BookImages/@x.Cart.Sach.HinhAnh" alt="product img"></a></td>
                                        <td class="product-name"><a href="#">@x.Cart.Sach.TenSach</a></td>
                                        <td class="product-price"><span class="amount">@x.BangGia.DonGia</span></td>
                                        <td class="product-quantity">
                                            <div class="form-group">
                                                <input name="SoLuong[]" type="number" class="form-control prc" value="@x.Cart.Amount" />
                                            </div>
                                        </td>
                                        <td class="product-subtotal">

                                            @x.GiaTong

                                        </td>
                                        @*<td class="product-remove"><a asp-action="XoaMatHang" asp-controller="ShoppingCart" asp-route-id="@x.Cart.CartId.ToString("yyyyMMddHHmmss")">X</a></td>*@
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    <div class="cartbox__btn">
                        
                        <ul class="cart__btn__list d-flex flex-wrap flex-md-nowrap flex-lg-nowrap justify-content-between">

                            <li>
                                <button type="submit">

                                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                            data-key="pk_test_ZbaQ1zrji4drQXzTPL0EHizQ00gg6Jj80V"
                                            data-name="LINKCreative"
                                            data-description="Product One ($10.00)"
                                            data-image="https://www.dropbox.com/s/3cz7kdvw7qh62jf/LINK_logo_512_red.png?dl=1"
                                            data-label="PayPall"
                                            data-allow-remember-me="false"
                                            data-locale="auto">
                                    </script>
                                </button>
                            </li>
                        </ul>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 offset-lg-6">
                <div class="cartbox__total__area">
                    @{
                        var Tong = 0;
                        var diemso = 0;
                        @foreach (var item in Model)
                        {
                            Tong += item.GiaTong;
                            diemso = item.Cart.Customer.DiemSo;
                        }
                    <div class="cart__total__amount">

                        @if (diemso >= 10000)
                        {
                            <span>Khuyến mãi Kim cương</span>
                            <span>20%</span>
                            <span>Tổng tiền</span>
                            <span>@(Tong - Tong * 20 / 100)</span>
                        }
                        else if (diemso >= 5000)
                        {
                            <span>Khuyến mãi vàng</span>
                            <span>10%</span>
                            <span>Tổng tiền</span>
                            <span>@(Tong - Tong * 10 / 100)</span>
                        }
                        else if (diemso >= 1000)
                        {
                            <span>Khuyến mãi bạc</span>
                            <span>5%</span>
                            <span>Tổng tiền</span>
                            <span>@(Tong - Tong * 5 / 100)</span>
                        }
                        else
                        {
                            <span>0%</span>
                            <span>Tổng tiền</span>
                            <span>@Tong</span>
                        }


                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- cart-main-area end -->
<!-- Footer Area -->

<!-- //Footer Area -->
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
        $('.form-group').on('input', '.prc', function () {
            var min = 1;
            $('.form-group .prc').each(function () {
               
                if ($(this).val() <= 0) {
                    $(this).val(min);
                }
            });
        });

    </script>
}