BookStore_Core/BookStore_Core/Models/ChiTietHoaDon.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BookStore_Core.Models
{
    public class ChiTietHoaDon
    {
        [Key]
        public int CTHDId { get; set; }
        public DateTime HoaDonId { get; set; }
        public string SachId { get; set; }
        public int SoLuong { get; set; }
        public int DanhGia { get; set; }
        public bool IsDanhGia { get; set; }
        public int TongTien { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}

BookStore_Core/BookStore_Core/Models/HoaDon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore_Core.Models
{
    public class HoaDon
    {
        [Key]
        public DateTime HoaDonId { get; set; }
        public string CustomerId { get; set; }
        public int TongTien { get; set; }
        public bool IsDanhGia { get; set; }
        public bool XacNhan { get; set; }
        public int TrangThai { get; set; }
        public virtual Customer Customer { get; set; }
        [NotMapped]
        public List<ChiTietHoaDon> ChiTietHoaDons { get; set; }
    }
}

BookStore_Core/BookStore_Core/Areas/Admin/Controllers/HoaDonsController.cs
using BookStore_Core.DAL;
using BookStore_Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore_Core.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/HoaDons")]
    public class HoaDonsController : Controller
    {
        private readonly BookStoreContext _context;

        public HoaDonsController(BookStoreContext context)
        {
            _context = context;
        }
        [Route("index")]
        // GET: Admin/HoaDons
        public IActionResult Index()
        {
            var hoaDon = _context.HoaDons.Include(m => m.Customer);
            return View(hoaDon);
        }
        [Route("Details")]
        // GET: Admin/HoaDons/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var chiTietHoaDon = await _context.ChiTietHoaDons.Include(p => p.Sach).Include(p => p.HoaDon).Where(p => p.HoaDonId.ToString("ddMMyyyyHHMMss") == id).ToListAsync();
            return View(chiTietHoaDon);
        }
        [Route("XacNhan")]
        // GET: Admin/HoaDons/Create
        public IActionResult XacNhan(string id)
        {
            var hoaDon = _context.HoaDons.FirstOrDefault(p => p.HoaDonId.ToString("ddMMyyyHHMMss") == id);
            var cthd = _context.ChiTietHoaDons.Include(p => p.Sach).Where(p => p.HoaDonId == hoaDon.HoaDonId);
            hoaDon.XacNhan = true;
            hoaDon.TrangThai = 0;
            _context.Update(hoaDon);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        [Route("XacNhanDaGiao")]
        public IActionResult XacNhanDaGiao(string id)
        {
            var hoaDon = _context.HoaDons.FirstOrDefault(p => p.HoaDonId.ToString("ddMMyyyHHMMss") == id);
            var cthd = _context.ChiTietHoaDons.Include(p => p.Sach).Where(p => p.HoaDonId == hoaDon.HoaDonId);
            //hoaDon.XacNhan = true;
            hoaDon.TrangThai = 1;
            _context.Update(hoaDon);
            _context.SaveChanges();
            int[] a = new int[8];
            foreach (var x in cthd)
            {
                var cttl = _context.LoaiSachCuThes.Include(p => p.LoaiSachTongQuat).FirstOrDefault(p => p.LoaiSachCTId == x.Sach.LoaiSachCTId);
                if (cttl.LoaiSachTongQuat.LoaiSachTQId == "1")
                {
                    a[0] += x.SoLuong;
                }
                else if (cttl.LoaiSachTongQuat.LoaiSachTQId == "2")
                {
                    a[1] += x.SoLuong;
                }
                else if (cttl.LoaiSachTongQuat.LoaiSachTQId == "3")
                {
                    a[2] += x.SoLuong;
                }
                else if (cttl.LoaiSachTongQuat.LoaiSachTQId == "4")
                {
                    a[3] += x.SoLuong;
                }
                else if (cttl.LoaiSachTongQuat.LoaiSachTQId == "5")
                {
                    a[4] += x.SoLuong;
                }
                else if (cttl.LoaiSachTongQuat.LoaiSachTQId == "6")
                {
                    a[5] += x.SoLuong;
                }
                else if (cttl.LoaiSachTongQuat.LoaiSachTQId == "7")
                {
                    a[6] += x.SoLuong;
                }
                else
                {
                    a[7] += x.SoLuong;
                }
            }
            var DTNgay = _context.DoanhThuNgays.FirstOrDefault(p => p.DoanhThuId.Date == hoaDon.HoaDonId.Date);
            if (DTNgay == null)
            {
                _context.Add(new DoanhThuNgay() { DoanhThuId = hoaDon.HoaDonId.Date, TongTien = hoaDon.TongTien, VanHoc = a[0], KinhTe = a[1], TamLy_KyNang = a[2], NuoiCon = a[3], SachThieuNhi = a[4], TieuSu_HoiKy = a[5], SGK = a[6], SachNgoaiNgu = a[7] });
                _context.SaveChanges();
            }
            else
            {
                DTNgay.TongTien += hoaDon.TongTien;
                DTNgay.VanHoc += a[0];
                DTNgay.KinhTe += a[1];
                DTNgay.TamLy_KyNang += a[2];
                DTNgay.NuoiCon += a[3];
                DTNgay.SachThieuNhi += a[4];
                DTNgay.TieuSu_HoiKy += a[5];
                DTNgay.SGK += a[6];
                DTNgay.SachNgoaiNgu += a[7];
                _context.Update(DTNgay);
                _context.SaveChanges();
            }


            var DTThang = _context.DoanhThuThangs.FirstOrDefault(p => p.DoanhThuId.Month == hoaDon.HoaDonId.Month && p.DoanhThuId.Year == hoaDon.HoaDonId.Year);
            if (DTThang == null)
            {
                string thang = hoaDon.HoaDonId.Year + "-" + hoaDon.HoaDonId.Month + "-" + "01";
                _context.Add(new DoanhThuThang() { DoanhThuId = Convert.ToDateTime(thang), TongTien = hoaDon.TongTien, VanHoc = a[0], KinhTe = a[1], TamLy_KyNang = a[2], NuoiCon = a[3], SachThieuNhi = a[4], TieuSu_HoiKy = a[5], SGK = a[6], SachNgoaiNgu = a[7] });
                _context.SaveChanges();
            }
            else
            {
                DTThang.TongTien += hoaDon.TongTien;
                DTThang.VanHoc += a[0];
                DTThang.KinhTe += a[1];
                DTThang.TamLy_KyNang += a[2];
                DTThang.NuoiCon += a[3];
                DTThang.SachThieuNhi += a[4];
                DTThang.TieuSu_HoiKy += a[5];
                DTThang.SGK += a[6];
                DTThang.SachNgoaiNgu += a[7];
                _context.Update(DTThang);
                _context.SaveChanges();
            }

            var DTNam = _context.DoanhThuNams.FirstOrDefault(p => p.DoanhThuId == hoaDon.HoaDonId.Year.ToString());
            if (DTNam == null)
            {
                _context.Add(new DoanhThuNam() { DoanhThuId = hoaDon.HoaDonId.Year.ToString(), TongTien = hoaDon.TongTien, VanHoc = a[0], KinhTe = a[1], TamLy_KyNang = a[2], NuoiCon = a[3], SachThieuNhi = a[4], TieuSu_HoiKy = a[5], SGK = a[6], SachNgoaiNgu = a[7] });
                _context.SaveChanges();
            }
            else
            {
                DTNam.TongTien += hoaDon.TongTien;
                DTNam.VanHoc += a[0];
                DTNam.KinhTe += a[1];
                DTNam.TamLy_KyNang += a[2];
                DTNam.NuoiCon += a[3];
                DTNam.SachThieuNhi += a[4];
                DTNam.TieuSu_HoiKy += a[5];
                DTNam.SGK += a[6];
                DTNam.SachNgoaiNgu += a[7]; _context.Update(DTNam);
                _context.SaveChanges();
            }

            var cus = _context.Customers.FirstOrDefault(p => p.CustomerId == hoaDon.CustomerId);
            cus.DiemSo = hoaDon.TongTien / 1000;
            _context.Customers.Update(cus);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [Route("BaoCaoNgay")]
        public IActionResult BaoCaoNgay()
        {
            return View(_context.DoanhThuNgays);
        }
        [Route("BaoCaoThang")]
        public IActionResult BaoCaoThang()
        {

            return View(_context.DoanhThuThangs);
        }
        [Route("BaoCaoNam")]
        public IActionResult BaoCaoNam()
        {

            return View(_context.DoanhThuNams);
        }
        public async Task<IActionResult> Delete(DateTime? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .FirstOrDefaultAsync(m => m.HoaDonId == id);
            if (hoaDon == null)
            {
                return NotFound();
            }

            return View(hoaDon);
        }

        // POST: Admin/HoaDons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(DateTime id)
        {
            var hoaDon = await _context.HoaDons.FindAsync(id);
            _context.HoaDons.Remove(hoaDon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoaDonExists(DateTime id)
        {
            return _context.HoaDons.Any(e => e.HoaDonId == id);
        }
        [Route("XuatExcel")]
        public IActionResult XuatExcel(string id)
        {
            if (id == "Ngày")
            {
                return File(FomatExcel(id), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "BaoCaoNgay.xlsx");

            }
            else if (id == "Tháng")
            {
                return File(FomatExcel(id), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "BaoCaoThang.xlsx");

            }
            else return File(FomatExcel(id), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "BaoCaoNam.xlsx");
        }

        public byte[] FomatExcel(string id)
        {
            string[] col_name = new string[] {
                "Ngày",
                "Văn học (Cuốn)",
                "Kinh tế (Cuốn)",
                "Tâm lý - Kỹ năng sống (Cuốn)",
                "Nuôi dạy con (Cuốn)",
                "Sách thiếu nhi (Cuốn)",
                "Tiểu sử - Hồi ký (Cuốn)",
                "Sách giáo khoa - Tham khảo (Cuốn",
                "Sách ngoại ngữ (cuốn)",
                "Tổng tiền"
            };
            //step 2: Create result byte array
            //byte[] result;
            //step 3: create a new package using memory safe structure
            using (var package = new ExcelPackage())
            {
                ExcelWorksheet worksheet = null;
                if (id == "Ngày")
                {
                    worksheet = package.Workbook.Worksheets.Add("BaoCaoNgay");
                    for (int i = 0; i < col_name.Length; i++)
                    {
                        worksheet.Cells[1, i + 1].Style.Font.Size = 14;

BookStore_Core/BookStore_Core/Views/HoaDons/ChiTietHoaDon.cshtml
@model IEnumerable<BookStore_Core.Models.ChiTietHoaDon>
@{
    ViewData["Title"] = "LichSuMuaHang";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}
<div class="ht__bradcaump__area bg-image--3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Shopping Cart</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="index.html">Home</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Shopping Cart</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- cart-main-area start -->
<div class="cart-main-area section-padding--lg bg--white">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 ol-lg-12">
                <form asp-action="KetThucThanhToan">
                    <div class="table-content wnro__table table-responsive">
                        <table>
                            <thead>
                                <tr class="title-top">
                                    <th class="product-name">Hình ảnh</th>
                                    <th class="product-name">Tên sách</th>
                                    <th class="product-quantity">Số lượng</th>
                                    <th class="product-name">Đánh giá</th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach (var x in Model)
                                {
                                <tr>
                                    <td class="product-name">
                                        <img src="~/BookImages/@x.Sach.HinhAnh" width="300" height="250" />
                                    </td>
                                    <td class="product-name">@x.Sach.TenSach</td>
                                    <td class="product-quantity">@x.SoLuong</td>
                                    @if (x.IsDanhGia)
                                    {
                                        <td class="product-name">@x.DanhGia sao</td>
                                    }
                                    else
                                    {
                                        <td class="product-name">
                                            <a asp-action="DanhGia" asp-controller="HoaDons" asp-route-id="@x.CTHDId">Đánh giá</a>
                                        </td>
                                    }

                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

BookStore_Core/BookStore_Core/Views/HoaDons/Create.cshtml
@model BookStore_Core.Models.HoaDon

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>HoaDon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HoaDonId" class="control-label"></label>
                <input asp-for="HoaDonId" class="form-control" />
                <span asp-validation-for="HoaDonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TongTien" class="control-label"></label>
                <input asp-for="TongTien" class="form-control" />
                <span asp-validation-for="TongTien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookStore_Core/BookStore_Core/Views/HoaDons/DanhGia.cshtml
@model BookStore_Core.Models.ChiTietHoaDon
@{
    ViewData["Title"] = "DanhGia";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/VoteStar/style.css">

<div class="page-blog-details section-padding--lg bg--white">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-12">
                <div class="blog-details content">
                    <div>
                        <br />
                        <br />
                        <dl class="row">

                            <dd class="col-sm-10">
                                <img src="~/BookImages/@Model.Sach.HinhAnh" style="height:350px; width:350px" />
                            </dd>
                        </dl>
                    </div>
                    <div class="comment_respond">
                        
                        <form asp-action="ChiTietHoaDon" method="post" class="comment__form">
                            <div id="full-stars-example-two">
                                <div class="rating-group">
                                    <input disabled checked class="rating__input rating__input--none" name="rating3" id="rating3-none" value="0" type="radio">
                                    <label aria-label="1 star" class="rating__label" for="rating3-1"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                    <input class="rating__input" name="rating3" id="rating3-1" value="1" type="radio">
                                    <label aria-label="2 stars" class="rating__label" for="rating3-2"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                    <input class="rating__input" name="rating3" id="rating3-2" value="2" type="radio">
                                    <label aria-label="3 stars" class="rating__label" for="rating3-3"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                    <input class="rating__input" name="rating3" id="rating3-3" value="3" type="radio">
                                    <label aria-label="4 stars" class="rating__label" for="rating3-4"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                    <input class="rating__input" name="rating3" id="rating3-4" value="4" type="radio">
                                    <label aria-label="5 stars" class="rating__label" for="rating3-5"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                                    <input class="rating__input" name="rating3" id="rating3-5" value="5" type="radio">
                                </div>
                                <p>@ViewBag.Loi</p>
                            </div>
                            <h3 class="reply_title">Đánh giá sao</h3>
                            <p style="font-family:Tahoma">Đánh giá của bạn về tác phẩm sau khi mua</p>
                            <div class="input__box">
                                <textarea name="comment" placeholder="Bình luận tại đây"></textarea>
                            </div>
                            <div class="submite__btn">
                                <button type="submit" asp-route-id="@Model.CTHDId"><a>Đánh giá</a></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BookStore_Core/BookStore_Core/Views/HoaDons/Delete.cshtml
@model BookStore_Core.Models.HoaDon

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HoaDon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongTien)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="HoaDonId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookStore_Core/BookStore_Core/Views/HoaDons/Details.cshtml
@model BookStore_Core.Models.HoaDon

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>HoaDon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongTien)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.HoaDonId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookStore_Core/BookStore_Core/Views/HoaDons/Edit.cshtml
@model BookStore_Core.Models.HoaDon

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>HoaDon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HoaDonId" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TongTien" class="control-label"></label>
                <input asp-for="TongTien" class="form-control" />
                <span asp-validation-for="TongTien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookStore_Core/BookStore_Core/Views/HoaDons/Index.cshtml
@model IEnumerable<BookStore_Core.Models.HoaDon>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TongTien)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TongTien)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.HoaDonId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.HoaDonId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.HoaDonId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BookStore_Core/BookStore_Core/Views/HoaDons/LichSuMuaHang.cshtml
@model IEnumerable<BookStore_Core.Models.HoaDon>
@{
    ViewData["Title"] = "LichSuMuaHang";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}
<div class="ht__bradcaump__area bg-image--3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Shopping Cart</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="index.html">Home</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Shopping Cart</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- cart-main-area start -->
<div class="cart-main-area section-padding--lg bg--white">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 ol-lg-12">
                <form asp-action="KetThucThanhToan">
                    <div class="table-content wnro__table table-responsive">
                        <table>
                            <thead>
                                <tr class="title-top">
                                    <th class="product-thumbnail">Ngày mua</th>
                                    <th class="product-quantity">Số lượng</th>
                                    <th class="product-price">Tổng tiền</th>
                                    <th class="product-name">Xuất hóa đơn</th>
                                    <th class="product-name">Chi tiết</th>
                                    <th class="product-name">Tình trạng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @{
                                    var i = 0;
                                    @foreach (var x in Model)
                                    {
                                <tr>
                                    <td class="product-thumbnail">@x.HoaDonId</td>
                                    <td class="product-quantity">@ViewBag.SoLuong[i]</td>
                                    <td class="product-price">@x.TongTien</td>
                                    <td class="product-price">
                                        <a asp-action="XuatHoaDon" asp-controller="HoaDons" asp-route-id="@x.HoaDonId.ToString("yyyyMMddHHmmss")">In</a>
                                    </td>
                                    <td class="product-price">
                                        <a asp-action="ChiTietHoaDon" asp-controller="HoaDons" asp-route-id="@x.HoaDonId.ToString("yyyyMMddHHmmss")">xem</a>
                                    </td>
                                    @if (x.TrangThai == 0)
                                    {
                                        <td class="product-remove">
                                            Đang giao
                                        </td>
                                    }
                                    else if (x.IsDanhGia)
                                    {
                                        <td class="product-remove">
                                            Đã đánh giá tất cả sản phẩm
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="product-remove">
                                            <a asp-action="ChiTietHoaDon" asp-controller="HoaDons" asp-route-id="@x.HoaDonId.ToString("yyyyMMddHHmmss")">Chưa đánh giá</a>
                                        </td>
                                    }

                                </tr>
                                        i++;
                                    }


                                }

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
</div>